name = "WordFrequencyDistributions"
uuid = "e54f717d-7b48-4a5e-b2d3-ea27d5093ee4"
authors = ["Michael Myers"]
version = "0.1.0"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Chain = "0.5"
SparseArrays = "1"
StatsBase = "0.34"
julia = "1.9"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
