name = "WordFrequencyDistributions"
uuid = "e54f717d-7b48-4a5e-b2d3-ea27d5093ee4"
authors = ["Michael Myers"]
version = "0.2.0"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34"
julia = "1.9"

[extras]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Chain", "Pkg", "Test"]
